#include "recording_save.h"
#include "recording_process.h"
#include <Windows.h>
#include <filesystem>
#include <iostream>
#include <thread>
#include <fstream>
#include <cmath>
extern "C" {
#include <libavformat/avformat.h>
}
using namespace clypdat;
namespace {
void require(bool value,const char* message){if(!value)throw std::runtime_error(message);}
std::filesystem::path executable(){wchar_t path[32768]{};require(GetModuleFileNameW(nullptr,path,DWORD(std::size(path)))>0,"Cannot resolve test executable");return path;}
std::filesystem::path ffmpeg(){auto directory=executable().parent_path();for(int i=0;i<8&&!directory.empty();++i){for(auto candidate:{directory/L"vendor/ffmpeg/ffmpeg.exe",directory/L"native/vendor/ffmpeg/ffmpeg.exe"})if(std::filesystem::is_regular_file(candidate))return candidate;directory=directory.parent_path();}throw std::runtime_error("Bundled ffmpeg.exe unavailable to session recovery test");}
std::shared_ptr<CaptureGeneration> parameters(const VideoEncoder& encoder){auto generation=std::make_shared<CaptureGeneration>();generation->id=1;generation->time_base=encoder.context().time_base;auto* codec=avcodec_parameters_alloc();require(codec!=nullptr&&avcodec_parameters_from_context(codec,&encoder.context())>=0,"Cannot copy session codec parameters");generation->codec={codec,CaptureCodecParametersDeleter{}};return generation;}
int crash_writer(const std::filesystem::path& output){
    VideoEncoderConfig config;config.width=64;config.height=64;config.fps=30;config.name="libx264";VideoEncoder encoder(config);auto generation=parameters(encoder);
    FullSessionWriter writer({output,{{"game","Game Audio",2,1,false},{"mic","Microphone",1,1,false},{"discord","Discord",2,1,false}}},generation);
    AVFrame* frame=av_frame_alloc();require(frame!=nullptr,"Cannot allocate fixture frame");frame->format=encoder.context().pix_fmt;frame->width=64;frame->height=64;require(av_frame_get_buffer(frame,32)>=0,"Cannot allocate fixture pixels");
    for(int i=0;i<100;++i){require(av_frame_make_writable(frame)>=0,"Cannot own fixture frame");for(int y=0;y<64;++y)memset(frame->data[0]+y*frame->linesize[0],16+i%180,64);for(int y=0;y<32;++y)memset(frame->data[1]+y*frame->linesize[1],128,64);frame->pts=int64_t(i)*1000000/30;for(auto& packet:encoder.submit(*frame))require(writer.video(generation,*packet),"Session rejected fixture video");for(const auto& lane:{"game","mic","discord"}){PcmBlock block;block.lane=lane;block.source=lane;block.generation=i<50?1:2;block.start_us=frame->pts;block.channels=block.lane=="mic"?1:2;block.sample_rate=48000;block.samples.resize(size_t(1600)*block.channels);for(size_t sample=0;sample<block.samples.size();++sample)block.samples[sample]=float(.25*std::sin(2*3.141592653589793*440*(i*1600+sample/block.channels)/48000));require(writer.audio(std::move(block)),"Session rejected fixture audio");}}
    av_frame_free(&frame);for(auto& packet:encoder.finish())require(writer.video(generation,*packet),"Session rejected delayed video");
    auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(10);while(writer.status().duration_us<3000000&&writer.status().error.empty()&&std::chrono::steady_clock::now()<deadline)std::this_thread::sleep_for(std::chrono::milliseconds(5));require(writer.status().error.empty()&&writer.status().duration_us>=3000000,"Session did not write recoverable fixture");std::cout<<"READY\n"<<std::flush;Sleep(60000);return 2;
}
void inspect_named(const std::filesystem::path& path){auto bytes=path.u8string();std::string name(bytes.begin(),bytes.end());AVFormatContext* input=nullptr;require(avformat_open_input(&input,name.c_str(),nullptr,nullptr)>=0,"Recovered session cannot open");struct Close{AVFormatContext* p;~Close(){avformat_close_input(&p);}} close{input};require(avformat_find_stream_info(input,nullptr)>=0&&input->duration>0,"Recovered session has no positive duration");require(input->nb_streams==4,"Recovered session lost a stream");const char* expected[]={"Game Audio","Microphone","Discord"};for(unsigned i=1;i<4;++i){auto* title=av_dict_get(input->streams[i]->metadata,"title",nullptr,0);auto* handler=av_dict_get(input->streams[i]->metadata,"handler_name",nullptr,0);require((title&&std::string(title->value)==expected[i-1])||(handler&&std::string(handler->value)==expected[i-1]),"Recovery changed ordered audio track names");}require(av_seek_frame(input,-1,input->duration/2,AVSEEK_FLAG_BACKWARD)>=0,"Recovered session cannot seek");}
void crash_test(const std::filesystem::path& root,const wchar_t* extension){auto output=root/(std::wstring(L"crashed")+extension);std::atomic_bool cancel=false;bool ready=false,terminated=false;std::string received;try{ProcessRunner::run(executable(),{L"--crash-writer",output.wstring()},cancel,std::chrono::seconds(20),[&](const uint8_t* bytes,size_t count){received.append(reinterpret_cast<const char*>(bytes),count);if(received.find("READY")!=std::string::npos){ready=true;cancel=true;}});}catch(...){terminated=true;}require(ready&&terminated,"Fixture child did not reach crash boundary");auto marker=output.wstring()+L".recording";HANDLE reclaim=CreateFileW(marker.c_str(),GENERIC_READ|GENERIC_WRITE,0,nullptr,OPEN_EXISTING,FILE_FLAG_DELETE_ON_CLOSE,nullptr);require(reclaim!=INVALID_HANDLE_VALUE,"Terminated writer retained recording lease");CloseHandle(reclaim);require(std::filesystem::exists(output.wstring()+L".interrupted"),"Interrupted recording marker missing");cancel=false;require(recover_recording(output,ffmpeg(),cancel),"Native interrupted recording recovery failed");require(!std::filesystem::exists(output.wstring()+L".interrupted"),"Recovery retained interruption marker");inspect_named(output);ProcessRunner::run(ffmpeg(),{L"-v",L"error",L"-i",output.wstring(),L"-map",L"0",L"-f",L"null",L"-"},cancel,std::chrono::seconds(20));}
void failure_test(const std::filesystem::path& root){VideoEncoderConfig config;config.width=64;config.height=64;config.fps=30;VideoEncoder encoder(config);auto generation=parameters(encoder);Packet packet(av_packet_alloc());require(av_new_packet(packet.get(),100)>=0,"Packet allocation failed");packet->pts=packet->dts=0;packet->flags=AV_PKT_FLAG_KEY;FullSessionConfig limited{root/L"overflow.mkv",{},1,1};FullSessionWriter overflow(limited,generation);require(!overflow.video(generation,*packet),"Full-session queue bound ignored");require(overflow.stop(),"Overflow session did not terminate");require(!overflow.status().error.empty(),"Overflow session did not report failure");require(!overflow.video(generation,*packet),"Failed session accepted later packets");auto obstruction=root/L"blocked";std::ofstream(obstruction).put('x');FullSessionWriter failed({obstruction/L"failed.mkv",{}},generation);require(failed.stop()&&!failed.status().error.empty(),"Session filesystem failure did not remain isolated");auto original=root/L"invalid.mp4";std::ofstream(original) << "preserve original";std::atomic_bool cancel=false;require(!recover_recording(original,ffmpeg(),cancel),"Invalid media recovery succeeded");std::ifstream input(original);std::string contents((std::istreambuf_iterator<char>(input)),{});require(contents=="preserve original","Failed recovery replaced original footage");}
void suppression_test(const std::filesystem::path& root){
    auto model=ffmpeg().parent_path().parent_path()/L"rnnoise/lq.rnnn";require(std::filesystem::is_regular_file(model),"Bundled RNNoise model unavailable");
    for(bool fail:{false,true}){std::mutex mutex;std::vector<PcmBlock> emitted;RecordingMicrophoneFilter filter(fail?root/L"missing-ffmpeg.exe":ffmpeg(),model,-45,[&](PcmBlock block){std::lock_guard lock(mutex);emitted.push_back(std::move(block));});for(int i=0;i<20;++i){PcmBlock block;block.lane="mic";block.source="default";block.generation=1;block.sample_rate=48000;block.channels=1;block.start_us=1000000+i*10000+(i>=10?20000:0);block.samples.resize(480,.25f);filter.submit(std::move(block));}auto barrier=filter.barrier();require(filter.stop(),"Microphone filter did not drain before stop");require(barrier.wait_for(std::chrono::seconds(1))==std::future_status::ready,"Accepted suppression barrier did not survive stop");barrier.get();size_t frames=0;int64_t prior=0;bool saw_gap=false;for(const auto& block:emitted){require(block.start_us>=prior,"Microphone suppression reordered source timestamps");if(prior&&block.start_us>prior+1)saw_gap=true;prior=block.start_us+block.duration_us();frames+=block.samples.size()/block.channels;for(float value:block.samples){require(std::isfinite(value),"Microphone filter produced invalid PCM");if(fail)require(value==.25f,"Suppression failure did not preserve unfiltered input");}}require(frames==9600,"Microphone filter lost samples at drain/fallback");require(saw_gap,"Microphone filter discarded source timestamp gap");}
}
}
int main(int argc,char** argv){try{if(argc==3&&std::string(argv[1])=="--crash-writer")return crash_writer(std::filesystem::path(argv[2]));auto root=std::filesystem::current_path()/(L"session-recovery-fixture-"+std::to_wstring(GetCurrentProcessId())+L"-"+std::to_wstring(GetTickCount64()));require(std::filesystem::create_directory(root),"Fixture directory already exists");struct Cleanup{std::filesystem::path path;~Cleanup(){std::error_code ignored;std::filesystem::remove_all(path,ignored);}} cleanup{root};failure_test(root);suppression_test(root);crash_test(root,L".mp4");crash_test(root,L".mkv");std::cout<<"Native MP4/MKV crash recovery, named tracks, suppression, queue and disk faults passed\n";return 0;}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
