namespace ClypDat.App.Services;

public sealed record ReplayBufferConfig(
    int DurationSeconds,
    int MaxHeight,
    int FrameRate,
    int CaptureX,
    int CaptureY,
    int CaptureWidth,
    int CaptureHeight,
    string ChatAudioDeviceName,
    string ChatAudioDeviceId,
    IReadOnlyList<string> ChatAudioProcessNames,
    IReadOnlyList<string> MicrophoneDeviceIds,
    string MicrophoneDeviceName,
    IReadOnlyList<string> GameAudioExcludedProcesses,
    string GameDisplayName,
    string GameExecutableName,
    string GameWindowTitle,
    string GameWindowClass,
    string Backend = "Auto",
    long GameWindowHandle = 0,
    bool FullSessionRecordingEnabled = false,
    string FullSessionRecordingFolder = "",
    string FullSessionVideoCodec = "H.264",
    int FullSessionQuotaGb = 0,
    bool FullSessionBackgroundFinalize = true,
    string ClipFileNameScheme = "Standard",
    string CustomClipFileNameTemplate = "{datetime:yyyy-MM-dd HH-mm-ss} - {title}",
    string LibraryFolder = "",
    // Native engine encoder controls. The hardware configuration is selected
    // automatically for the selected codec and available encoder.
    string VideoCodec = "H.264",
    string EncoderMode = "GPU",
    string EncoderProfile = "Automatic",
    int BitrateMbps = 15,
    string FrameRateMode = "CFR",
    string CaptureSource = "Game",
    string CaptureMonitorDeviceName = "",
    bool CaptureCursor = false,
    string ProcessPriority = "Normal",
    string SaveReplayHotkey = ClypDat.Core.Settings.AppSettings.DefaultSaveReplayHotkey,
    string FramePacingMode = "CFR",
    IReadOnlyDictionary<string, int>? AdditionalAudioProcesses = null,
    int GameAudioVolumePercent = 100,
    int MicrophoneVolumePercent = 100,
    string MicrophoneChannelMode = "Mono",
    bool MicrophoneNoiseSuppressionEnabled = false,
    double MicrophoneNoiseGateThresholdDb = -100,
    bool AdaptiveFrameRateProtectionEnabled = false,
    string FullSessionHotkey = "F8",
    string FullSessionContainer = "MKV",
    bool ReplayHdrCompatibilityEnabled = true);

